import type { Run } from './types'

export const mockRuns: Run[] = [
  {
    id: 'run-001',
    tenant: 'acme-corp',
    region: 'us-east-1',
    problem_description: 'High latency detected in payment processing service. Response times increased from 200ms to 2500ms over the last 30 minutes.',
    status: 'awaiting_approval',
    current_step: 'Awaiting approval to scale up payment-service replicas',
    created_at: '2026-04-20T10:30:00Z',
    updated_at: '2026-04-20T10:45:00Z',
    timeline: [
      {
        id: 'evt-1',
        timestamp: '2026-04-20T10:30:00Z',
        type: 'status_change',
        title: 'Run Started',
        description: 'Incident triage initiated for high latency in payment service',
      },
      {
        id: 'evt-2',
        timestamp: '2026-04-20T10:31:00Z',
        type: 'observation',
        title: 'Metrics Collected',
        description: 'Gathered latency metrics from the last 2 hours',
      },
      {
        id: 'evt-3',
        timestamp: '2026-04-20T10:33:00Z',
        type: 'tool_execution',
        title: 'Query Prometheus',
        description: 'Executed PromQL query to analyze latency patterns',
      },
      {
        id: 'evt-4',
        timestamp: '2026-04-20T10:35:00Z',
        type: 'hypothesis',
        title: 'Hypothesis Generated',
        description: 'CPU saturation on payment-service pods likely causing increased latency',
      },
      {
        id: 'evt-5',
        timestamp: '2026-04-20T10:40:00Z',
        type: 'tool_execution',
        title: 'Kubernetes Status Check',
        description: 'Verified pod resource utilization and limits',
      },
      {
        id: 'evt-6',
        timestamp: '2026-04-20T10:45:00Z',
        type: 'approval_request',
        title: 'Approval Required',
        description: 'Requesting approval to scale payment-service from 3 to 6 replicas',
      },
    ],
    observations: [
      {
        id: 'obs-1',
        timestamp: '2026-04-20T10:31:00Z',
        source: 'prometheus',
        content: 'P99 latency increased from 180ms to 2450ms at 10:15 UTC',
        severity: 'critical',
      },
      {
        id: 'obs-2',
        timestamp: '2026-04-20T10:32:00Z',
        source: 'prometheus',
        content: 'CPU utilization at 94% across all payment-service pods',
        severity: 'critical',
      },
      {
        id: 'obs-3',
        timestamp: '2026-04-20T10:33:00Z',
        source: 'kubernetes',
        content: 'No pod restarts or OOM kills detected in the last hour',
        severity: 'info',
      },
      {
        id: 'obs-4',
        timestamp: '2026-04-20T10:34:00Z',
        source: 'datadog',
        content: 'Request rate increased 3x compared to yesterday at the same time',
        severity: 'warning',
      },
    ],
    hypotheses: [
      {
        id: 'hyp-1',
        timestamp: '2026-04-20T10:35:00Z',
        description: 'CPU saturation causing request queuing and increased latency',
        confidence: 0.85,
        supporting_evidence: [
          'CPU at 94% utilization',
          'No memory pressure detected',
          'Latency correlates with CPU spike',
        ],
        status: 'confirmed',
      },
      {
        id: 'hyp-2',
        timestamp: '2026-04-20T10:36:00Z',
        description: 'Database connection pool exhaustion',
        confidence: 0.15,
        supporting_evidence: [
          'Connection count stable at 45/100',
        ],
        status: 'rejected',
      },
    ],
    tool_outputs: [
      {
        id: 'tool-1',
        timestamp: '2026-04-20T10:33:00Z',
        tool_name: 'prometheus_query',
        input: { query: 'histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{service="payment-service"}[5m]))' },
        output: '2.45 (seconds)',
        status: 'success',
        duration_ms: 234,
      },
      {
        id: 'tool-2',
        timestamp: '2026-04-20T10:40:00Z',
        tool_name: 'kubectl_get_pods',
        input: { namespace: 'production', selector: 'app=payment-service' },
        output: 'NAME                              READY   STATUS    RESTARTS   CPU\npayment-service-7d9f8b6c5-abc12   1/1     Running   0          94%\npayment-service-7d9f8b6c5-def34   1/1     Running   0          93%\npayment-service-7d9f8b6c5-ghi56   1/1     Running   0          95%',
        status: 'success',
        duration_ms: 1523,
      },
      {
        id: 'tool-3',
        timestamp: '2026-04-20T10:42:00Z',
        tool_name: 'datadog_metrics',
        input: { metric: 'request_rate', service: 'payment-service', period: '24h' },
        output: 'Current: 15,234 req/min\nYesterday same time: 4,892 req/min\nIncrease: 211%',
        status: 'success',
        duration_ms: 892,
      },
    ],
  },
  {
    id: 'run-002',
    tenant: 'techstart-io',
    region: 'eu-west-1',
    problem_description: 'Database connection errors spiking on user-service. Error rate increased to 5% of requests.',
    status: 'running',
    current_step: 'Analyzing database connection patterns',
    created_at: '2026-04-20T11:00:00Z',
    updated_at: '2026-04-20T11:05:00Z',
    timeline: [
      {
        id: 'evt-1',
        timestamp: '2026-04-20T11:00:00Z',
        type: 'status_change',
        title: 'Run Started',
        description: 'Incident triage initiated for database connection errors',
      },
      {
        id: 'evt-2',
        timestamp: '2026-04-20T11:02:00Z',
        type: 'observation',
        title: 'Error Logs Collected',
        description: 'Gathered error logs from user-service pods',
      },
      {
        id: 'evt-3',
        timestamp: '2026-04-20T11:05:00Z',
        type: 'tool_execution',
        title: 'Database Health Check',
        description: 'Checking PostgreSQL connection pool status',
      },
    ],
    observations: [
      {
        id: 'obs-1',
        timestamp: '2026-04-20T11:02:00Z',
        source: 'application_logs',
        content: 'Connection timeout errors: "FATAL: too many connections for role user_service"',
        severity: 'critical',
      },
      {
        id: 'obs-2',
        timestamp: '2026-04-20T11:03:00Z',
        source: 'postgres',
        content: 'Active connections: 98/100 (max_connections)',
        severity: 'warning',
      },
    ],
    hypotheses: [
      {
        id: 'hyp-1',
        timestamp: '2026-04-20T11:04:00Z',
        description: 'Connection pool exhaustion due to connection leaks',
        confidence: 0.72,
        supporting_evidence: [
          'Connections near max limit',
          'Error message indicates too many connections',
        ],
        status: 'investigating',
      },
    ],
    tool_outputs: [
      {
        id: 'tool-1',
        timestamp: '2026-04-20T11:05:00Z',
        tool_name: 'psql_status',
        input: { query: 'SELECT count(*) FROM pg_stat_activity' },
        output: '98',
        status: 'success',
        duration_ms: 45,
      },
    ],
  },
  {
    id: 'run-003',
    tenant: 'fintech-plus',
    region: 'ap-southeast-1',
    problem_description: 'Memory leak suspected in analytics-worker service. Memory usage growing linearly over time.',
    status: 'completed',
    current_step: 'Resolution applied successfully',
    created_at: '2026-04-20T08:00:00Z',
    updated_at: '2026-04-20T09:30:00Z',
    timeline: [
      {
        id: 'evt-1',
        timestamp: '2026-04-20T08:00:00Z',
        type: 'status_change',
        title: 'Run Started',
        description: 'Incident triage initiated for memory leak investigation',
      },
      {
        id: 'evt-2',
        timestamp: '2026-04-20T08:30:00Z',
        type: 'hypothesis',
        title: 'Root Cause Identified',
        description: 'Memory leak in event buffer not being cleared',
      },
      {
        id: 'evt-3',
        timestamp: '2026-04-20T09:00:00Z',
        type: 'approval_request',
        title: 'Restart Approved',
        description: 'Rolling restart approved and initiated',
      },
      {
        id: 'evt-4',
        timestamp: '2026-04-20T09:30:00Z',
        type: 'status_change',
        title: 'Resolved',
        description: 'Memory usage normalized after rolling restart',
      },
    ],
    observations: [],
    hypotheses: [],
    tool_outputs: [],
  },
  {
    id: 'run-004',
    tenant: 'retail-hub',
    region: 'us-west-2',
    problem_description: 'SSL certificate expiring in 48 hours for api.retail-hub.com',
    status: 'pending',
    current_step: 'Waiting in queue',
    created_at: '2026-04-20T11:15:00Z',
    updated_at: '2026-04-20T11:15:00Z',
    timeline: [
      {
        id: 'evt-1',
        timestamp: '2026-04-20T11:15:00Z',
        type: 'status_change',
        title: 'Run Created',
        description: 'Pending automated certificate renewal check',
      },
    ],
    observations: [],
    hypotheses: [],
    tool_outputs: [],
  },
  {
    id: 'run-005',
    tenant: 'acme-corp',
    region: 'us-east-1',
    problem_description: 'Disk space running low on logging cluster. Currently at 89% utilization.',
    status: 'failed',
    current_step: 'Failed to execute cleanup - insufficient permissions',
    created_at: '2026-04-19T22:00:00Z',
    updated_at: '2026-04-19T22:45:00Z',
    timeline: [
      {
        id: 'evt-1',
        timestamp: '2026-04-19T22:00:00Z',
        type: 'status_change',
        title: 'Run Started',
        description: 'Disk space cleanup initiated',
      },
      {
        id: 'evt-2',
        timestamp: '2026-04-19T22:45:00Z',
        type: 'status_change',
        title: 'Run Failed',
        description: 'Cleanup script failed due to missing IAM permissions',
      },
    ],
    observations: [],
    hypotheses: [],
    tool_outputs: [],
  },
]

export function getRunById(id: string): Run | undefined {
  return mockRuns.find(run => run.id === id)
}
